# Generated by Django 5.1.2 on 2024-10-31 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ['prioridad'], 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AlterModelOptions(
            name='tarea',
            options={'ordering': ['prioridad'], 'verbose_name_plural': 'Tareas'},
        ),
        migrations.AddField(
            model_name='tarea',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.proyecto'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='departamentos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.departamento'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='proveedores',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.proveedor'),
        ),
    ]
