# Generated by Django 5.1.2 on 2024-10-31 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_remove_proyecto_departamentos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('Por Iniciar', 'Por Iniciar'), ('En Curso', 'En Curso'), ('Suspendido', 'Suspendido'), ('Finalizado', 'Finalizado')], default='Por Iniciar', max_length=255),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='departamentos',
            field=models.ManyToManyField(blank=True, null=True, to='database.departamento'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='proveedores',
            field=models.ManyToManyField(blank=True, null=True, to='database.proveedor'),
        ),
    ]
