# Generated by Django 5.1.2 on 2024-10-31 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_proyecto_estado_alter_proyecto_departamentos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='limite',
            field=models.DateField(blank=True, null=True),
        ),
    ]
