# Generated by Django 5.1.2 on 2024-11-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_alter_proyecto_inicio_alter_proyecto_limite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
